
name: Test Automation workflow

on:
 schedule:
 - cron: 30 06 * * *
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation framework with maven
      run: mvn test -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
      
    - name: Upload Test logs as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: screenshots
       path: screenshots/

    - name: Upload Test Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: htnl-report
       path: report.html

    - name: Tests Execution Status
      run: echo "Test execution Completed"
      
    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html  public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/ || true
        ls -l

    - name: Deploy 🚀
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.ATF0208 }}
        clean: true

       
       

       
       
      

   
