
name: Test Automation workflow

on:
 schedule:
 - cron: 30 06 * * *
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation framework with maven
      run: mvn test -X -Dbrowser=chrome -DisLambdatest=false -DisHeadless=false
      
    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test logs
       path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test Reports
       path: report.html

    - name: Tests Execution Status
      run: echo "Test execution Completed"

       
       

       
       
      

   
